### ISSUE TITLE
DB Autocommit performance

### ISSUE THREAD

**Issue by thread-ncraig** [ac0v/burstcoin#11]
[FINE] 2017-08-23 12:14:46 com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.mariadb.jdbc.MariaDbConnection@3783eeba

the Hikari config is initially set to autocommit false,
Db.Java line 109,
but then changed to true when the getConnection function is called
Db.Java line 166. 

this will adversely affect the performance of the DB layer.

**Comment by 4nt1g0** [comment]
I don't see an issue here. The `getConnection` function returns a connection with `autocommit = true` which makes sense for single statements. The `beginTransaction` function disables the autocommit for usage with multiple statements. Either way has nothing to do with performance.

I'm closing this issue, feel free to reopen it if you don't agree with me.
