### ISSUE TITLE
Latest release not correct?

### ISSUE THREAD

**Issue by PsyDafke** [ac0v/burstcoin#14]
Hi,

I downloaded 1.3.2cg from the releases page, but it still shows as 1.3.0cg in the WebUI.
Also mentions 'NRS is outdated'. Could it be that the wrong jar was attached to the release?
Haven't got into compiling it from source yet, but seems to work and node stays 'up' besides the version issue.

Thanks for any advice,

David

**Comment by ac0v** [comment]
As of today, 1.3.4cg has been released - all version numbers should be correct in there. It is also available as debian/ubuntu package using https://package.cryptoguru.org
