### ISSUE TITLE
Use https URLs for inclusion of external resources.

### ISSUE THREAD

**Issue by systemofapwne** [ac0v/burstcoin#17]
Running the Wallet in HTTPS-Mode requires to include all external resources also to come from a secure connection. Otherwise, it will throw an error when loading the website (Mixed Content).
By editing the index.html and change line 10 and 21 to require external JS from https, the wallet loads without complaining about mixed content.
Further more, crowdfunding is broken on SSL. To fix it, one needs to change all http-calls in nrs.crowdfunding.js to point to https instead. One should implement a simple http/https wrapper.
One should also check all http-calls in all JS files, if they need to be changed to http/https, depending on how the wallet is ran.

**Comment by chrulri** [comment]
Ran into the same issue today. For patch proposal see #26.
