### ISSUE TITLE
trying to run in docker

### ISSUE THREAD

**Issue by cchance27** [ac0v/burstcoin#25]
tried making a simple ubuntu/debian based dockerfile for your installer but ran into issue A. mysql needs to be seperate and their doesnt seem to be a way to install burstcoincg without mysql, and i cant figure out a way to do an unattended install so that the "do you want me to setup database" doesn't get asked and the install can finish / build.

Any chance of a dockerfile or ubuntu package that just clean installs the burstcoincg minus mysql

**Comment by ac0v** [comment]
It would be possible in general to run multiple services inside of one docker container using supervised or something similar.

If you want to not setup the database itself using dbconfig-common you could use:

```sh
DEBIAN_FRONTEND=noninteractive apt-get install -yq burstcoincg
```
I think you would have to pressed a `/etc/burstcoincg/nxt.properties` file.

But I think using ubuntu or debian in a container should be avoided if possible. I prefer something like alpine for that. For that purpose I've created a small docker-compose project at https://github.com/ac0v/burstcoin-mariadb-docker
